server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:221801334&221801230/PaperCV/src/main/resources/sqlite/papercv.db
    username:
    password:


mybatis:
  mapper-locations: classpath:mapper/*.xml


