server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: classpath:sqlite/papercv.db
    username:
    password:


mybatis:
  mapper-locations: classpath:mapper/*.xml


